[package]
name = "microbit-fizz-buzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.6"
cortex-m-rt = "0.7.2"
microbit-v2 = "0.13.0"
nrf52833-hal = "0.16.0"
panic-halt = "0.2.0"
